INPUT_FILE: small_test.fastq.gz
DEMUX_RECOVERY: /ebio/abt6_projects7/small_projects/ibezrukov2/demux_recovery/demux_recovery.py
SAMPLES_FILE: samples.yaml
#LINES_PER_FILE: 400000
LINES_PER_FILE: 400
SPLIT_OUT: Splitted